### ISSUE TITLE
App crashes for every transition call

### ISSUE THREAD

**Issue by nigel-wells** [Telerik-Verified-Plugins/NativePageTransitions#147]
I've tried all the help and examples everyone has mentioned but still not getting anywhere. 
I've tried debugging on device as well as 3 different versions of the Android emulator and get the same issue on them all. Due to everyones success it is bound to be me but I'm struggling to diagnose what it is.

Here is the log from Android Device Monitor as soon as the app crashes:

```
07-07 22:15:40.374: I/chromium(9682): [INFO:CONSOLE(26794)] "[native transition] $stateChangeStart", source: http://10.0.0.52:8100/lib/ionic/js/ionic.bundle.js (26794)
07-07 22:15:40.374: I/chromium(9682): [INFO:CONSOLE(26794)] "[native transition]", source: http://10.0.0.52:8100/lib/ionic/js/ionic.bundle.js (26794)
07-07 22:15:40.374: I/chromium(9682): [INFO:CONSOLE(124)] "Probably running inside a companion app, your app may crash if your html file is not in the root!", source: http://10.0.0.52:8100/plugins/com.telerik.plugins.nativepagetransitions/www/NativePageTransitions.js (124)
07-07 22:15:40.384: D/dalvikvm(9682): GC_FOR_ALLOC freed 153K, 14% free 10220K/11812K, paused 4ms, total 4ms
07-07 22:15:40.384: I/dalvikvm-heap(9682): Grow heap (frag case) to 17.169MB for 7464972-byte allocation
07-07 22:15:40.384: D/dalvikvm(9682): GC_FOR_ALLOC freed 4613K, 33% free 12897K/19104K, paused 2ms, total 2ms
07-07 22:15:40.434: D/dalvikvm(9682): GC_FOR_ALLOC freed 2384K, 45% free 10517K/19104K, paused 2ms, total 2ms
07-07 22:15:40.434: I/dalvikvm-heap(9682): Grow heap (frag case) to 17.459MB for 7464972-byte allocation
07-07 22:15:40.434: D/dalvikvm(9682): GC_FOR_ALLOC freed <1K, 33% free 17807K/26396K, paused 2ms, total 2ms
07-07 22:15:40.444: D/AndroidRuntime(9682): Shutting down VM
07-07 22:15:40.444: W/dalvikvm(9682): threadid=1: thread exiting with uncaught exception (group=0x9cd71b20)
07-07 22:15:40.444: E/AndroidRuntime(9682): FATAL EXCEPTION: main
07-07 22:15:40.444: E/AndroidRuntime(9682): Process: com.ionicframework.lorryland423317, PID: 9682
07-07 22:15:40.444: E/AndroidRuntime(9682): java.lang.IllegalArgumentException: delay < 0: -1
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at java.util.Timer.schedule(Timer.java:457)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at com.telerik.plugins.nativepagetransitions.NativePageTransitions.doSlideTransition(NativePageTransitions.java:439)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at com.telerik.plugins.nativepagetransitions.NativePageTransitions.access$1000(NativePageTransitions.java:27)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at com.telerik.plugins.nativepagetransitions.NativePageTransitions$1.run(NativePageTransitions.java:190)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at android.os.Handler.handleCallback(Handler.java:733)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at android.os.Looper.loop(Looper.java:136)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at java.lang.reflect.Method.invoke(Method.java:515)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
07-07 22:15:40.444: E/AndroidRuntime(9682): 	at dalvik.system.NativeStart.main(Native Method)
07-07 22:15:40.444: W/ActivityManager(1591):   Force finishing activity com.ionicframework.lorryland423317/.MainActivity
```

When inspecting via Chrome, or outputting console messages via IDE, there is never any errors - just standard debugging from the plugin stating that transitions are on and ionic transitions are off.

I've got a fresh install of everything (from today) so in theory I'll be on all the latest versions.

Any ideas?

**Comment by nigel-wells** [comment]
This is resolved now - removed the plugin and added it back up and it is working now. I guess it somehow downloaded an older version perhaps - though I was just copying and pasting from the documentation so perhaps something needs an update there.
