### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by netzzeit** [Telerik-Verified-Plugins/NativePageTransitions#165]
Hey,

Google Play Console gives me this error from time to time:

**java.lang.NullPointerException:
com.telerik.plugins.nativepagetransitions.NativePageTransitions.getBitmap**

I'm using Phonegap Build and I have absolutely no idea what that is supposed to mean. Seems to be an android only issue.

Can anyone help me?

Thanks a lot!!!

More info from the Play Console:

`java.lang.NullPointerException: 
  at android.graphics.Bitmap.createBitmap(Bitmap.java:737)
  at com.telerik.plugins.nativepagetransitions.NativePageTransitions.getBitmap(NativePageTransitions.java:724)
  at com.telerik.plugins.nativepagetransitions.NativePageTransitions.access$400(NativePageTransitions.java:27)
  at com.telerik.plugins.nativepagetransitions.NativePageTransitions$2.run(NativePageTransitions.java:167)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:145)
  at android.app.ActivityThread.main(ActivityThread.java:5951)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)`

**Comment by pilladooo** [comment]
I have exactly the same problem. Did you solved it?

**Comment by netzzeit** [comment]
Unfortunately not :( The problem still exists and I have absolutely no idea what to do about it...

**Comment by sevans-ge** [comment]
Running into the issue as well since we've dropped support for Crosswalk and using strictly the native engine. And looking at the source code, it makes sense why since it's in the "not Crosswalk" branch.

Looking at [Bitmap.java in the Android source](https://android.googlesource.com/platform/frameworks/base/+/master/graphics/java/android/graphics/Bitmap.java#729) it looks like the NPE is likely coming from the call to `src.getWidth()`. Which would ultimately mean the [`view.getDrawingCache()`](https://github.com/Telerik-Verified-Plugins/NativePageTransitions/blob/master/src/android/NativePageTransitions.java#L724) call ultimately is returning a null object. Following the chain down from [`getDrawingCache()`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/View.java#18170) to [`getDrawingCache(bool)`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/View.java#18203) it is possible for a null Bitmap to come back.

Still now sure why that flag is set, but I'm going to hazard a guess that's the root of the issue.
