### ISSUE TITLE
crosswalk crash again

### ISSUE THREAD

**Issue by scottsut** [Telerik-Verified-Plugins/NativePageTransitions#65]
i run my app with crosswalk and NativePageTransitions well in last two month, today i upgrade my ionic cli to 1.6.4 and android build tools to 23.0.1, then rebuild my app, it crashed when loading. i use logcat got these infomations:

```bash
D/XWalkLib( 5295): Pre init xwalk core in com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve class class org.xwalk.core.XWalkPreferences to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve method setValue to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve class class org.xwalk.core.XWalkPreferences to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve method setValue to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve class class org.xwalk.core.XWalkPreferences to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve method setValue to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve class class org.xwalk.core.XWalkPreferences to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve method setValue to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve object class org.crosswalk.engine.XWalkCordovaView to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve object class org.crosswalk.engine.XWalkCordovaResourceClient to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve method setResourceClient to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve object class org.crosswalk.engine.XWalkCordovaUiClient to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/XWalkLib( 5295): Reserve method setUIClient to com.guohuaigroup.GuoHuaiDevApp.MainActivity
D/AndroidRuntime( 5295): Shutting down VM
W/dalvikvm( 5295): threadid=1: thread exiting with uncaught exception (group=0x41665808)
E/AndroidRuntime( 5295): FATAL EXCEPTION: main
E/AndroidRuntime( 5295): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.guohuaigroup.GuoHuaiDevApp/com.guohuaigroup.GuoHuaiDevApp.MainActivity}: java.lang.UnsupportedOperationException: setLayerType
E/AndroidRuntime( 5295): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
E/AndroidRuntime( 5295): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
E/AndroidRuntime( 5295): 	at android.app.ActivityThread.access$900(ActivityThread.java:148)
E/AndroidRuntime( 5295): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
E/AndroidRuntime( 5295): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5295): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 5295): 	at android.app.ActivityThread.main(ActivityThread.java:5473)
E/AndroidRuntime( 5295): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5295): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 5295): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:804)
E/AndroidRuntime( 5295): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
E/AndroidRuntime( 5295): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 5295): Caused by: java.lang.UnsupportedOperationException: setLayerType
E/AndroidRuntime( 5295): 	at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:57)
E/AndroidRuntime( 5295): 	at org.xwalk.core.XWalkView.setLayerType(XWalkView.java:596)
E/AndroidRuntime( 5295): 	at com.telerik.plugins.nativepagetransitions.NativePageTransitions.enableHardwareAcceleration(NativePageTransitions.java:706)
E/AndroidRuntime( 5295): 	at com.telerik.plugins.nativepagetransitions.NativePageTransitions.initialize(NativePageTransitions.java:98)
E/AndroidRuntime( 5295): 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:54)
E/AndroidRuntime( 5295): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
E/AndroidRuntime( 5295): 	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:95)
E/AndroidRuntime( 5295): 	at org.apache.cordova.PluginManager.init(PluginManager.java:84)
E/AndroidRuntime( 5295): 	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
E/AndroidRuntime( 5295): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:138)
E/AndroidRuntime( 5295): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:208)
E/AndroidRuntime( 5295): 	at com.guohuaigroup.GuoHuaiDevApp.MainActivity.onCreate(MainActivity.java:32)
E/AndroidRuntime( 5295): 	at android.app.Activity.performCreate(Activity.java:5234)
E/AndroidRuntime( 5295): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 5295): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
E/AndroidRuntime( 5295): 	... 11 more
W/ActivityManager(  927):   Force finishing activity com.guohuaigroup.GuoHuaiDevApp/.MainActivity
W/DropBoxManagerService(  927): Dropping: data_app_crash (2400 > 0 bytes)
I/WindowManager(  927): Screenshot Window{42a37880 u0 Starting com.guohuaigroup.GuoHuaiDevApp} was all black! mSurfaceLayer=22010 minLayer=22010 maxLayer=22010
```

can somebody figure it out?

**Comment by EddyVerbruggen** [comment]
As a quick fix, if you have access to the native Android code, can you go into `NativePageTransitions.java` and comment out line 706?

**Comment by scottsut** [comment]
It works ! @EddyVerbruggen Thank you very much!

**Comment by EddyVerbruggen** [comment]
Awesome!

I'm preparing a fix, perhaps you're willing to test it by changing lines 705-707 by this:

```java
      if (BEFORE_KITKAT && !isCrosswalk) {
        getView().setLayerType(View.LAYER_TYPE_SOFTWARE, null);
      }
```

**Comment by scottsut** [comment]
@EddyVerbruggen ok, I'm going to test it and keep watching.
