### ISSUE TITLE
App crashes on start on older devices with crosswalk 14+

### ISSUE THREAD

**Issue by RobinsonAndrew** [Telerik-Verified-Plugins/NativePageTransitions#74]
I'm building an app using Ionic (Ionic CLI version 1.6.5 and Cordova version 5.3.3). With this I'm using Crosswalk on Android. The native transition plugin was working on all my test devices albeit with some freezing issues on an older device (a Samsung Galaxy Nexus on Android 4.3). I believe at this stage I was using crosswalk 12.41.296.5.

I noticed there were newer versions of crosswalk out and wanted to test them so tried to update to version 14. This works fine on newer devices with Android 4.4+ but crashes on app start up on older devices (Samsung Galaxy Nexus on Android 4.3 and Sony Xperia on Android 4.0.4). Crosswalk 14+ also seems to be the default that is used with the new crosswalk plugin which is added when using - 'ionic platform add android'.

The app works fine with the plugin without crosswalk and also works fine with just crosswalk without the plugin.

Below is a stack trace of the crash. From this it seems to be an issue with any Android version < 4.4 rather than the devices.

```
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{co.yavi.dev/co.yavi.dev.MainActivity}: java.lang.UnsupportedOperationException: setLayerType
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsupportedOperationException: setLayerType
            at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:57)
            at org.xwalk.core.XWalkView.setLayerType(XWalkView.java:615)
            at com.telerik.plugins.nativepagetransitions.NativePageTransitions.enableHardwareAcceleration(NativePageTransitions.java:706)
            at com.telerik.plugins.nativepagetransitions.NativePageTransitions.initialize(NativePageTransitions.java:98)
            at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:54)
            at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
            at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:95)
            at org.apache.cordova.PluginManager.init(PluginManager.java:84)
            at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
            at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:150)
            at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:220)
            at co.yavi.dev.MainActivity.onCreate(MainActivity.java:32)
            at android.app.Activity.performCreate(Activity.java:5133)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```

This seems to be related https://crosswalk-project.org/jira/browse/XWALK-5021

**Comment by NgYueHong** [comment]
+1

I also experience the same issue when try to install the app with crosswalk 14+ and NativePageTransitions plugin on old android 4.1 lenovo device, the app crash instantly.

**Comment by EddyVerbruggen** [comment]
I'll look into this today!
@NgYueHong do you have a similar stacktrace?

**Comment by NgYueHong** [comment]
I am wiling to help. But, how can I get the stacktrace?

**Comment by EddyVerbruggen** [comment]
@NgYueHong thanks - I will try to fix the stacktrace of @RobinsonAndrew and we'll see if that fixes your issue as well. If not I will get back to you ;)

**Comment by vagrant1991** [comment]
@EddyVerbruggen   The same issue   on Galaxy Nexus 4.1.2 

i  found it's  casued by this line

getView().setLayerType(View.LAYER_TYPE_SOFTWARE, null);

**Comment by vagrant1991** [comment]
@EddyVerbruggen  the similar stacktrace. it's ok on Nexus 5  5.1.1

**Comment by EddyVerbruggen** [comment]
Should be OK in 0.4.3, but make sure you set `<preference name="CrosswalkAnimatable" value="true" />` in `config.xml`.

**Comment by Titoine** [comment]
Hi,
I still have the problem even with `<preference name="CrosswalkAnimatable" value="true" />`
Crosswalk  1.3.1
Android 4.1.2
Plugin 0.5.2
work great with older version of crosswalk.
```
10-25 23:29:41.987  18811-18811/com.myapp.toto D/dalvikvm﹕ start new thread
10-25 23:29:41.987  18811-18831/com.myapp.toto D/dalvikvm﹕ threadid=11: notify debugger
10-25 23:29:41.987  18811-18831/com.myapp.toto D/dalvikvm﹕ threadid=11 (android.hardware.SystemSensorManager$SensorThread): calling run()
10-25 23:29:41.995  18811-18811/com.myapp.toto D/AndroidRuntime﹕ Shutting down VM
10-25 23:29:41.995  18811-18811/com.myapp.toto W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40e8e908)
10-25 23:29:41.997  18811-18811/com.myapp.toto E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.toto/com.myapp.toto.MainActivity}: java.lang.UnsupportedOperationException: setLayerType
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2189)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2216)
            at android.app.ActivityThread.access$600(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5000)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsupportedOperationException: setLayerType
            at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:57)
            at org.xwalk.core.XWalkView.setLayerType(XWalkView.java:615)
            at com.telerik.plugins.nativepagetransitions.NativePageTransitions.enableHardwareAcceleration(NativePageTransitions.java:723)
            at com.telerik.plugins.nativepagetransitions.NativePageTransitions.initialize(NativePageTransitions.java:101)
            at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:54)
            at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
            at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:95)
            at org.apache.cordova.PluginManager.init(PluginManager.java:84)
            at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
            at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:138)
            at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:208)
            at com.myapp.toto.MainActivity.onCreate(MainActivity.java:32)
            at android.app.Activity.performCreate(Activity.java:5020)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2216)
            at android.app.ActivityThread.access$600(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5000)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
            at dalvik.system.NativeStart.main(Native Method)
10-25 23:29:42.291  18811-18817/com.myapp.toto D/jdwp﹕ processIncoming
10-25 23:29:42.291  18811-18817/com.myapp.toto D/jdwp﹕ handlePacket : cmd=0x1, cmdSet=0xC7, len=0x14, id=0x40029183, flags=0x0, dataLen=0x9
```

**Comment by EddyVerbruggen** [comment]
@Titoine thanks for the stacktrace, let's continue in #82.
